ALTER TABLE `tbl_prj_gbif_pilot_b` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_brnu` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_gat` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_gjo` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_gzu` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_hal` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_je` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_lagu` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_lz` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_mjg` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_tbi` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_tgu` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_w` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `tbl_prj_gbif_pilot_wu` CHANGE `copyright` `copyright` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `tbl_prj_gbif_pilot_b`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_brnu`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_gat`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_gjo`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_gzu`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_hal`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_je`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_lagu`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_lz`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_mjg`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_tbi`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_tgu`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_w`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
ALTER TABLE `tbl_prj_gbif_pilot_wu`  ADD `multimedia_object_format` VARCHAR(50) NOT NULL AFTER `rights_url`;
